server:
  port: 8080
spring:
  application:
    name: Study
  quartz:
    job-store-type: JDBC
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyselfScheduler
            instanceId: AUTO
          jobStore:
            dataSource: myDS
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          dataSource:
            myDS:
              driver: com.mysql.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/ceshi?useSSL=true
              user: root
              password: 12345
              maxConnections: 5